version: '3'
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - ./elk-data:/var/lib/elasticsearch

  cyborg:
    build: .
    tty: true
    environment:
          CYBORG_LOGGER_ELK_ENABLED: 'true'
          CYBORG_LOGGER_ELK_INDEX: cyborg
          CYBORG_LOGGER_ELK_ADDRESS: http://elk:9200

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana